"""Initial migration with AI support

Revision ID: d640d6f52531
Revises: 
Create Date: 2026-01-06 22:09:29.569698

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd640d6f52531'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('code_snippets', sa.JSON(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('primary_language', sa.String(length=100), nullable=True),
    sa.Column('framework', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('licence', sa.String(length=100), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('found_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('dedupe_key', sa.String(length=500), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('ai_primary_language', sa.String(length=100), nullable=True),
    sa.Column('ai_framework', sa.String(length=100), nullable=True),
    sa.Column('ai_quality_score', sa.Float(), nullable=True),
    sa.Column('ai_extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dedupe_key', 'knowledge_items', ['dedupe_key'], unique=False)
    op.create_index('idx_published_at', 'knowledge_items', ['published_at'], unique=False)
    op.create_index('idx_source_type_language', 'knowledge_items', ['source_type', 'primary_language'], unique=False)
    op.create_index(op.f('ix_knowledge_items_dedupe_key'), 'knowledge_items', ['dedupe_key'], unique=True)
    op.create_index(op.f('ix_knowledge_items_framework'), 'knowledge_items', ['framework'], unique=False)
    op.create_index(op.f('ix_knowledge_items_primary_language'), 'knowledge_items', ['primary_language'], unique=False)
    op.create_index(op.f('ix_knowledge_items_published_at'), 'knowledge_items', ['published_at'], unique=False)
    op.create_index(op.f('ix_knowledge_items_source_type'), 'knowledge_items', ['source_type'], unique=False)
    op.create_table('saved_searches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('primary_language', sa.String(length=100), nullable=True),
    sa.Column('framework', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('match_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_searches')
    op.drop_index(op.f('ix_knowledge_items_source_type'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_published_at'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_primary_language'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_framework'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_dedupe_key'), table_name='knowledge_items')
    op.drop_index('idx_source_type_language', table_name='knowledge_items')
    op.drop_index('idx_published_at', table_name='knowledge_items')
    op.drop_index('idx_dedupe_key', table_name='knowledge_items')
    op.drop_table('knowledge_items')
    # ### end Alembic commands ###

